### ISSUE TITLE
团队oa v1.7上线在即等待处理bug

### ISSUE THREAD

**Issue by iRuxu** [JX3BOX/jx3box-player#8]
## 面板属性细节
藏剑的面板属性，根据心法来判定取哪个武器的。

当mount_id为10144时，取轻剑的数值（即uPos为0的武器）
当mount_id为10145时，取重剑的数值（即uPos为1的武器）

**Comment by iRuxu** [comment]
## 实装无法显示
![image](https://user-images.githubusercontent.com/8476969/124351726-a765b900-dc2e-11eb-804b-868b8ed9efee.png)
实装组件后，目前无法显示属性部分。
具体路由为src/role/viewRole.vue 引入 本库src/Player.vue

**Comment by Kaviilee** [comment]
> ## 实装无法显示
> ![image](https://user-images.githubusercontent.com/8476969/124351726-a765b900-dc2e-11eb-804b-868b8ed9efee.png)
> 实装组件后，目前无法显示属性部分。
> 具体路由为src/role/viewRole.vue 引入 本库src/Player.vue

心法表有问题，已修复
